# Copyright (C) 2005 - 2021 Settlers Freaks <sf-team at siedler25.org>
#
# SPDX-License-Identifier: GPL-2.0-or-later

on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Extract tag name
        id: get_tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      - name: Set filename
        id: filename
        run: echo "archive=uWebSockets-${{steps.get_tag.outputs.tag}}.tar.gz" >> $GITHUB_OUTPUT
      - name: Create source distribution
        run: |
          set -x
          git submodule update --init
          git rev-parse HEAD > revision.txt
          
          NAME="uWebSockets-${{steps.get_tag.outputs.tag}}"
          
          mkdir "/tmp/${NAME}"
          cp -r * "/tmp/$NAME"
          mv "/tmp/${NAME}" .
          
          # Cleanup
          find "${NAME}" -name '.git*' -exec rm -rv {} \; || true
          
          # Archive
          tar -czf ${{steps.filename.outputs.archive}} "${NAME}"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            uWebSockets forked with CMake integration

            - ${{steps.filename.outputs.archive}} contains all source files including the submodules
          draft: false
          prerelease: false
      - name: Upload source distribution
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{steps.filename.outputs.archive}}
          asset_name: ${{steps.filename.outputs.archive}}
          asset_content_type: application/tar.gz